const receitas = [
    { id: 1, nome: 'Pão de Queijo com Goiabada', imagem: 'https://diariodonordeste.verdesmares.com.br/image/contentid/policy:1.3228473:1652117238/P%C3%A3o%20de%20queijo%20com%20goiabada.jpg?f=4x3&$p$f=0b36325', nivel: 'Média', tempo: '45min', categoria: 'Salgados',
porcoes: '(6 porções)',  ingredientes: ' 200 ml de óleo;\n 300 ml de leite;\n 300 g de polvilho doce;\n 100 g de polvilho azedo;\n 1 colher (sobremesa) de sal;\n 350 g de queijo mussarela ralado;\n 150 g de goiabada;\n 100 g de queijo parmesão ralado;\n 2 ovos;\n 150 g de cream cheese.',
preparo: '1. Junte o óleo e o leite em uma panela no fogo.\n2. Misture bem e espere ferver.\n3. Em um recipiente, junte o polvilho azedo, o doce, o sal e a mistura de leite ainda quente.\n4. Misture tudo muito bem e junte o parmesão e a mussarela.\n5. Coloque os ovos e, com as mãos, misture tudo.\n6. Abra essa massa em uma tábua e recheie com a goiabada e o cream cheese.\n7. Dica: deixe o cream cheese por pelo menos uns 30 minutos no freezer para ajudar a rechear.\n8. Feche as bolinhas e modele a gosto.\n9. Coloque em uma forma e leve para assar por 25 minutos a 230° C.'},
    { id: 2, nome: 'Rocambole Romeu e Julieta', imagem: 'https://static.itdg.com.br/images/640-420/895cbfdcf906865158be9ae46b925463/146515-original.jpg', nivel: 'Difícil', tempo: '1h', categoria: 'Doces, Massas',
    porcoes: '(14 porções)', ingredientes: ' 5 colheres de sopa de Óleo de soja Soya;\n 6 colheres de sopa de leite;\n 3/4 xícara de açúcar;\n 4 colheres de sopa de queijo parmesão ralado;\n porção de margarina para untar e farinha de trigo para polvilhar;\n 200 g de goiabada picada;\n 1/3 xícara de chocolate branco picado;\n 2 colheres de sopa de açúcar de confeiteiro;\n 3 colheres de sopa de água;\n 3 ovos, separados em gema e clara;\n 3/4 xícara de farinha de trigo;\n 1/2 colher de sopa de fermento químico em pó;\n açúcar para polvilhar a gosto;\n 5 colheres de sopa de água ou suco de laranja;\n 1 copo requeijão consistente.',
    preparo: '1. Pão-de-ló: Em uma batedeira leve a água, o leite, o óleo de soja Soya a gema e o açúcar para bater até obtenção de um creme homogêneo. Retire da batedeira, coloque em uma vasilha, adicione a farinha de trigo, o fermento em pó, o queijo parmesão e misture bem. Bata as claras em neve e misture delicadamente à massa. Em assadeira medindo 40 x 30 cm, untada e polvilhada ou forrada com papel manteiga, coloque a massa, espalhe bem e leve para assar em forno preaquecido, à temperatura de 200ºC, por 20 minutos.\n2. Retire do forno e reserve.\n3. Recheio: Em uma panela, leve a goiabada e a água ou suco de laranja para aquecer até que a goiabada derreta e se torne uma pasta. Retire do fogo, deixe esfriar e reserve.\n4. Cobertura: Derreta o chocolate em micro-ondas. Em batedeira leve os ingredientes da cobertura para bater até obtenção de um creme. Leve para gelar.\n5. Montagem: Desenforme a massa sobre uma folha de papel manteiga ou pano limpo, retire o papel manteiga do pão-de-ló e passe a goiabada por toda a superfície. Enrole o rocambole pressionando o suficiente para que fique firme. Leve à geladeira por 30 a 45 minutos. Retire o papel, decore com a cobertura e sirva.'},
    { id: 3, nome: 'Queijadinha com Goiabada', imagem: 'https://guiadacozinha.com.br/wp-content/uploads/2019/10/queijadinha-com-goiabada-34283.jpg', nivel: 'Fácil', tempo: '50min', categoria: 'Pudins, flans',
porcoes: '(20 porções)', ingredientes: ' 1 xícara de coco ralado;\n 2 gemas;\n 1 colher (sopa) de queijo ralado;\n 1 lata de leite condensado.',
preparo: '1. Misture todos os ingredientes em uma tigela.\n2. Em seguida, despeje o conteúdo até a metade de forminhas de cupcake (que possam ser levadas ao forno).\n3. Coloque quadradinhos de goiabada no meio da massa que será levada ao forno.\n4. Adicione mais massa, até tampar a goiabada.\n 5. Leve ao forno baixo por 40 minutos.'},
];

export default receitas;